### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by cankaya07** [Aidaho12/haproxy-wi#49]
i am getting an error when i click show button on the map menu.

here is the detail:
mv: cannot stat 'map.png': No such file or directory 
Node 'frontend main *:5000\n' has no position.

**Comment by Aidaho12** [comment]
Old haproxy config syntaxis ) I sort of fixed this bug, fixed one more time)

**Comment by Aidaho12** [comment]
Fixed, update and try

**Comment by Aidaho12** [comment]
You checked prev bugs? if alright, then close them please

**Comment by cankaya07** [comment]
what did you change on haproxy config my problem still persist.

**Comment by Aidaho12** [comment]
You updated?
--
Отправлено из Mail.Ru для Android понедельник, 01 октября 2018г., 19:39 +06:00 от Can KAYA  notifications@github.com :

**Comment by cankaya07** [comment]
yes i updated my whole project on the server.

**Comment by Aidaho12** [comment]
Show me config
--
Отправлено из Mail.Ru для Android понедельник, 01 октября 2018г., 19:43 +06:00 от Can KAYA  notifications@github.com :

**Comment by cankaya07** [comment]
This config file created for test purpose. working same machine with this GUI.
`#---------------------------------------------------------------------
# Example configuration for a possible web application.  See the
# full configuration options online.
#
#   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #   test3
    log 127.0.0.1 local0 info

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    #stats socket /var/lib/haproxy/stats

    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    #server-state-file /etc/haproxy/haproxy/haproxy.state

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000
    #load-server-state-from-file global

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main *:5000
    acl url_static       path_beg       -i /static /images /javascript /styleshe                                                                                                                                                  ets
    acl url_static       path_end       -i .jpg .gif .png .css .js

    use_backend static          if url_static
    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------
backend static
    balance     roundrobin
    server      static 127.0.0.1:4331 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
    server  app1 127.0.0.1:5001 check
    server  app2 127.0.0.1:5002 check
    server  app3 127.0.0.1:5003 check
    server  app4 127.0.0.1:5004 check


listen  stats   10.0.20.200:1903
        mode            http
        log             global

        maxconn 10

        clitimeout      100s
        srvtimeout      100s
        contimeout      100s
        timeout queue   100s

        stats enable
        stats hide-version
        stats refresh 30s
        stats show-node
        stats auth admin:password
        stats uri  /haproxy?stats
        stats admin if TRUE
`

**Comment by Aidaho12** [comment]
Fixed, update and try
